v2 Event handler
SandboxPowered/SimpleEventHandler pull request #2
Opened 2020-07-27 08:58 UTC by TheCodedOne

2020-07-27 11:51 UTC, MsRandom commented on src/main/java/org/sandboxpowered/eventhandler/ResettableEventHandler.java
> +        subscribers.values().forEach(Set::clear);
Wouldn't the subscriber sets be deallocated anyways when the subscribers map is cleared? if so why clear each one manually?

2020-07-27 11:51 UTC, MsRandom commented on src/main/java/org/sandboxpowered/eventhandler/exception/CancellationException.java
> +package org.sandboxpowered.eventhandler.exception;
Does this need an entire package when it's only one class?

2020-07-27 11:51 UTC, MsRandom commented on src/test/java/org/sandboxpowered/eventhandler/test/EventHandlerTest.java
> +        ((ResettableEventHandler<OnTest>) EVENT_HANDLER).reset();
The type of EVENT_HANDLER should be changed instead of casting

2020-07-27 11:51 UTC, MsRandom commented on src/main/java/org/sandboxpowered/eventhandler/CallbackInfo.java
> +public class CallbackInfo implements BooleanSupplier {
I'm guessing by the example that this will only be on events that need it, if so why have an isCancellable? as events that don't have cancelling can just not add this to their event, and if it's for the return then shouldn't CallbackInfoReturnable have a different base? since then there wouldn't autocomplete for cancelling on events that don't support it(and it would also remove the need for a CancellationException)

2020-07-27 11:52 UTC, MsRandom commented on src/main/java/org/sandboxpowered/eventhandler/exception/CancellationException.java
> +package org.sandboxpowered.eventhandler.exception;
Same for the Priority enum

2020-07-27 12:09 UTC, TheCodedOne commented on src/main/java/org/sandboxpowered/eventhandler/ResettableEventHandler.java
> +        subscribers.values().forEach(Set::clear);
I did it because I wasn't sure if that actually was the case or not

2020-07-27 13:05 UTC, MsRandom commented on src/main/java/org/sandboxpowered/eventhandler/ResettableEventHandler.java
> +        subscribers.values().forEach(Set::clear);
I did some tests, it appears that it uses the same amount of memory with both options but clearing each set manually takes 86-88% more time(with a sample size of 1 million), and 93-95% more time with a sample size of 100, so I think it's best to not do that, although both sample sizes are unlikely to happen in-game

2020-07-29 00:48 UTC, UpcraftLP requested changes

2020-07-29 00:48 UTC, UpcraftLP commented on src/main/java/org/sandboxpowered/eventhandler/Cancellable.java
> +public class Cancellable implements BooleanSupplier {
This probably should not implement BooleanSupplier.

2020-07-29 00:53 UTC, MsRandom commented on src/main/java/org/sandboxpowered/eventhandler/Cancellable.java
> +public class Cancellable implements BooleanSupplier {
Pretty sure that's to allow this
https://github.com/SandboxPowered/SimpleEventHandler/blob/feature/v2/src/main/java/org/sandboxpowered/eventhandler/ResettableEventHandler.java#L44

2020-07-31 09:30 UTC, TheCodedOne commented on src/main/java/org/sandboxpowered/eventhandler/Cancellable.java
> +public class Cancellable implements BooleanSupplier {
Yeah, its to make it more generic so if for some reason we want something that isn't the cancellable object to indicate an event has been cancelled (e.g. once a result has been accepted)

2020-07-31 09:52 UTC, Boundarybreaker commented on src/main/java/org/sandboxpowered/eventhandler/EventHandler.java
> +    default <R> R post(Function<T, R> trFunction, BiFunction<R, R, R> rComparator) {
Should `R` be in the class generics, or are we allowing events to post with arbitrary return types?

2020-07-31 09:52 UTC, Boundarybreaker commented on src/main/java/org/sandboxpowered/eventhandler/EventHandler.java
> +    <R> R post(Function<T, R> trFunction, BiFunction<R, R, R> rComparator, BooleanSupplier isCancelled);
Pass `Cancellable` instead of `BooleanSupplier`?

2020-07-31 09:52 UTC, Boundarybreaker commented on src/main/java/org/sandboxpowered/eventhandler/Priority.java
> +public enum Priority {
For some reason I don't like the concept of enum-based priority, but I can't think of anything much better.

2020-07-31 09:52 UTC, Boundarybreaker commented on src/main/java/org/sandboxpowered/eventhandler/EventHandler.java
> +    default void subscribe(T eventCall) {
I kinda wish that event listeners were named for debugging/inspection purposes, but that'd complicate stuff a lot.

2020-07-31 09:52 UTC, Boundarybreaker commented on src/main/java/org/sandboxpowered/eventhandler/Returnable.java
> +public class Returnable<V> {
Should this maybe extend `Cancellable`, since events already have capacity for returning a type?

2020-07-31 09:56 UTC, TheCodedOne commented on src/main/java/org/sandboxpowered/eventhandler/EventHandler.java
> +    default <R> R post(Function<T, R> trFunction, BiFunction<R, R, R> rComparator) {
they should probably be class generics the issue with it is, not all events will have return types & as such don't need a generic  that wont be used & could just confuse users & java itself.

2020-07-31 09:56 UTC, TheCodedOne commented on src/main/java/org/sandboxpowered/eventhandler/EventHandler.java
> +    <R> R post(Function<T, R> trFunction, BiFunction<R, R, R> rComparator, BooleanSupplier isCancelled);
https://github.com/SandboxPowered/SimpleEventHandler/pull/2#discussion_r461973916

2020-07-31 09:57 UTC, TheCodedOne commented on src/main/java/org/sandboxpowered/eventhandler/Returnable.java
> +public class Returnable<V> {
But having a return doesnt mean they're cancellable

2020-07-31 09:57 UTC, Boundarybreaker commented on src/main/java/org/sandboxpowered/eventhandler/EventHandler.java
> +    default <R> R post(Function<T, R> trFunction, BiFunction<R, R, R> rComparator) {
that's what `Void` is for, iirc.

2020-07-31 10:56 UTC, TheCodedOne commented on src/main/java/org/sandboxpowered/eventhandler/EventHandler.java
> +    default <R> R post(Function<T, R> trFunction, BiFunction<R, R, R> rComparator) {
would require returning null rather than just an actual void method

2020-07-31 10:57 UTC, TheCodedOne commented on src/main/java/org/sandboxpowered/eventhandler/Priority.java
> +public enum Priority {
thing is realistically the amount of priorities we set in the enum is far more than will actually be used, we could switch it to an integer-based priority system but that will not be that useful & would just be inefficient

2020-07-31 11:06 UTC, UpcraftLP requested changes

2020-07-31 11:06 UTC, UpcraftLP commented on Jenkinsfile
> +}
newline for consistency

2020-07-31 11:06 UTC, UpcraftLP commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5.1-all.zip
do we really need full gradle documentation here? I think the binary-only distribution would do fine.

2020-07-31 11:06 UTC, UpcraftLP commented on build.gradle
> +}
newline for consistency

2020-07-31 11:06 UTC, UpcraftLP commented on build.gradle
> +    implementation group: 'com.google.guava', name: 'guava', version: '21.0'
for consistency use the short variant (`com.google.guava:guava:21.0`)

2020-07-31 11:06 UTC, UpcraftLP commented on src/main/java/org/sandboxpowered/eventhandler/ResettableEventHandler.java
> +}
newline for consistency

2020-07-31 11:09 UTC, UpcraftLP approved these changes

2020-07-31 11:10 UTC, Boundarybreaker commented on src/main/java/org/sandboxpowered/eventhandler/Priority.java
> +public enum Priority {
yeah, exactly

2020-07-31 11:10 UTC, Boundarybreaker commented on src/main/java/org/sandboxpowered/eventhandler/EventHandler.java
> +    default <R> R post(Function<T, R> trFunction, BiFunction<R, R, R> rComparator) {
oh fair

2020-07-31 11:11 UTC, LemmaEOF approved these changes

2020-07-31 12:08 UTC, merged