Add a returnable cancellable implementation
SandboxPowered/SimpleEventHandler pull request #3
Opened 2020-09-16 15:18 UTC by TheCodedOne

2020-09-16 18:52 UTC, UpcraftLP requested changes

2020-09-16 18:52 UTC, UpcraftLP commented on src/main/java/org/sandboxpowered/eventhandler/BooleanFunction.java
> +public interface BooleanFunction<T> {
i.e. a `Predicate`

2020-09-17 07:26 UTC, MsRandom requested changes

2020-09-17 07:26 UTC, MsRandom commented on src/main/java/org/sandboxpowered/eventhandler/Cancellable.java
> +    BooleanSupplier ALWAYS_FALSE = () -> false;
Isn't this field no longer used?

2020-09-18 10:16 UTC, Boundarybreaker requested changes

2020-09-18 10:16 UTC, Boundarybreaker commented on src/main/java/org/sandboxpowered/eventhandler/EventHandler.java
>  public interface EventHandler<T> {
`returnable` should probably be `postReturnable` and `cancellable` should probably be `postCancellable`

2020-09-18 14:23 UTC, TheCodedOne commented on src/main/java/org/sandboxpowered/eventhandler/BooleanFunction.java
> +public interface BooleanFunction<T> {
i always forget which java function interface is which

2020-09-21 13:09 UTC, MsRandom approved these changes

2020-09-21 13:45 UTC, Boundarybreaker approved these changes

2020-09-22 23:49 UTC, UpcraftLP approved these changes

2020-09-27 14:59 UTC, merged